# Generated by Django 5.0.6 on 2024-06-21 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUC', models.CharField(blank=True, max_length=45, null=True)),
                ('DNI', models.CharField(blank=True, max_length=45, null=True)),
                ('NOMBRE', models.CharField(blank=True, max_length=45, null=True)),
                ('APELLIDO', models.CharField(blank=True, max_length=45, null=True)),
                ('EMPRESA', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Columnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_haz', models.CharField(blank=True, max_length=45, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=45, null=True)),
                ('ancho_banda', models.CharField(blank=True, max_length=45, null=True)),
                ('amortiguamiento', models.CharField(blank=True, max_length=45, null=True)),
                ('modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('ganancia', models.CharField(blank=True, max_length=45, null=True)),
                ('velocidad', models.CharField(blank=True, max_length=45, null=True)),
                ('retardo', models.CharField(blank=True, max_length=45, null=True)),
                ('diametro', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('material', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=45)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Fajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('nPoleas', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('iddatos', models.CharField(max_length=45, unique=True)),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.columnas')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.filas')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=45, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.documentos')),
            ],
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.parametros')),
            ],
        ),
        migrations.CreateModel(
            name='Poleas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('faja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.fajas')),
            ],
        ),
        migrations.CreateModel(
            name='PoleasProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.poleas')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.procesoinspeccion')),
            ],
        ),
        migrations.AddField(
            model_name='parametros',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.procesoinspeccion'),
        ),
        migrations.CreateModel(
            name='FajasProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.fajas')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.procesoinspeccion')),
            ],
        ),
        migrations.AddField(
            model_name='documentos',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.procesoinspeccion'),
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfilas', models.IntegerField(blank=True, null=True)),
                ('ncol', models.IntegerField(blank=True, null=True)),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.mediciones')),
            ],
        ),
        migrations.AddField(
            model_name='filas',
            name='tabla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.tabla'),
        ),
        migrations.AddField(
            model_name='columnas',
            name='tabla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.tabla'),
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='documentos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.usuarios'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.usuarios'),
        ),
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversoltdb.usuarios')),
            ],
        ),
    ]
